// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship['id']]: ContentRelationshipFieldWithData<
      TSubRelationship['customtypes'],
      TLang
    >
  } & // Group
  {
    [TGroup in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
      : never
  } & // Other fields
  {
    [TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
      ? TData[TFieldKey]
      : never
  }

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
      TLang
    >
  >
}[Exclude<TCustomType[number], string>['id']]

type BlogListingDocumentDataSlicesSlice = BlogHomeSlice

/**
 * Content for Blog Listing documents
 */
interface BlogListingDocumentData {
  /**
   * Slice Zone field in *Blog Listing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_listing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogListingDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_listing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Blog Listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_listing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Blog Listing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_listing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Blog Listing document from Prismic
 *
 * - **API ID**: `blog_listing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogListingDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<BlogListingDocumentData>,
  'blog_listing',
  Lang
>

type BlogPageDocumentDataSlicesSlice = BioSlice | MarkdownContentSlice

/**
 * Content for Dynamic Page documents
 */
interface BlogPageDocumentData {
  /**
   * Slice Zone field in *Dynamic Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Dynamic Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Dynamic Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Dynamic Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Dynamic Page document from Prismic
 *
 * - **API ID**: `blog_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<BlogPageDocumentData>,
  'blog_page',
  Lang
>

type BlogPageNewDocumentDataSlicesSlice = MarkdownContentSlice

/**
 * Content for Blog Page New documents
 */
interface BlogPageNewDocumentData {
  /**
   * Slice Zone field in *Blog Page New*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page_new.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogPageNewDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Page New*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_page_new.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Blog Page New*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_page_new.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Blog Page New*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page_new.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Blog Page New document from Prismic
 *
 * - **API ID**: `blog_page_new`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPageNewDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<BlogPageNewDocumentData>,
  'blog_page_new',
  Lang
>

type ContactUsDocumentDataSlicesSlice = ContactUsSlice

/**
 * Content for Contact Us documents
 */
interface ContactUsDocumentData {
  /**
   * Slice Zone field in *Contact Us*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContactUsDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact_us.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Contact Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact_us.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Contact Us*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Contact Us document from Prismic
 *
 * - **API ID**: `contact_us`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactUsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<ContactUsDocumentData>,
  'contact_us',
  Lang
>

type FooterDocumentDataSlicesSlice = FooterSlice

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice> /**
   * Meta Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: footer.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: footer.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<FooterDocumentData>,
  'footer',
  Lang
>

type HeaderDocumentDataSlicesSlice = NavbarSlice

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Slice Zone field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice> /**
   * Meta Title field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: header.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: header.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<HeaderDocumentData>,
  'header',
  Lang
>

type LandingDocumentDataSlicesSlice =
  | FooterSlice
  | ServiceSectionSlice
  | ProcessSectionSlice
  | TestimonialsSectionSlice
  | WhyDomainSectionSlice
  | FaqSectionSlice
  | MasteredSectionSlice
  | AdvisorSectionSlice
  | MembershipSectionSlice
  | FeaturedSectionSlice
  | NavbarSlice
  | HeroSlice

/**
 * Content for Landing documents
 */
interface LandingDocumentData {
  /**
   * is_waitlist_mode field in *Landing*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: landing.is_waitlist_mode
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_waitlist_mode: prismic.BooleanField

  /**
   * Slice Zone field in *Landing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LandingDocumentDataSlicesSlice> /**
   * Meta Title field in *Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Landing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Landing document from Prismic
 *
 * - **API ID**: `landing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<LandingDocumentData>,
  'landing',
  Lang
>

type OurProcessDocumentDataSlicesSlice = OurProcessSlice

/**
 * Content for Our Process documents
 */
interface OurProcessDocumentData {
  /**
   * Slice Zone field in *Our Process*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: our_process.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<OurProcessDocumentDataSlicesSlice> /**
   * Meta Title field in *Our Process*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: our_process.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Our Process*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: our_process.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Our Process*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_process.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Our Process document from Prismic
 *
 * - **API ID**: `our_process`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OurProcessDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<OurProcessDocumentData>,
  'our_process',
  Lang
>

type PricingPageDocumentDataSlicesSlice = PricingPageSlice

/**
 * Content for Pricing Page documents
 */
interface PricingPageDocumentData {
  /**
   * Slice Zone field in *Pricing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PricingPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Pricing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pricing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Pricing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pricing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Pricing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Pricing Page document from Prismic
 *
 * - **API ID**: `pricing_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PricingPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<PricingPageDocumentData>,
  'pricing_page',
  Lang
>

type PrivacyPolicyDocumentDataSlicesSlice =
  | HeroSlice
  | ProcessSectionSlice
  | MasteredSectionSlice
  | MembershipSectionSlice
  | WhyDomainSectionSlice
  | TestimonialsSectionSlice
  | ServiceSectionSlice
  | FooterSlice
  | FaqSectionSlice
  | AdvisorSectionSlice
  | FeaturedSectionSlice
  | NavbarSlice
  | MarkdownContentSlice

/**
 * Content for Privacy Policy documents
 */
interface PrivacyPolicyDocumentData {
  /**
   * Slice Zone field in *Privacy Policy*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PrivacyPolicyDocumentDataSlicesSlice> /**
   * Meta Title field in *Privacy Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: privacy_policy.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Privacy Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: privacy_policy.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Privacy Policy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Privacy Policy document from Prismic
 *
 * - **API ID**: `privacy_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyPolicyDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<PrivacyPolicyDocumentData>,
  'privacy_policy',
  Lang
>

type TermOfServicesDocumentDataSlicesSlice =
  | HeroSlice
  | WhyDomainSectionSlice
  | ProcessSectionSlice
  | TestimonialsSectionSlice
  | ServiceSectionSlice
  | FooterSlice
  | MembershipSectionSlice
  | MasteredSectionSlice
  | FeaturedSectionSlice
  | FaqSectionSlice
  | AdvisorSectionSlice
  | MarkdownContentSlice
  | NavbarSlice

/**
 * Content for Term of Services documents
 */
interface TermOfServicesDocumentData {
  /**
   * Slice Zone field in *Term of Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: term_of_services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TermOfServicesDocumentDataSlicesSlice> /**
   * Meta Title field in *Term of Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: term_of_services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Term of Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: term_of_services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Term of Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: term_of_services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Term of Services document from Prismic
 *
 * - **API ID**: `term_of_services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TermOfServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<TermOfServicesDocumentData>, 'term_of_services', Lang>

export type AllDocumentTypes =
  | BlogListingDocument
  | BlogPageDocument
  | BlogPageNewDocument
  | ContactUsDocument
  | FooterDocument
  | HeaderDocument
  | LandingDocument
  | OurProcessDocument
  | PricingPageDocument
  | PrivacyPolicyDocument
  | TermOfServicesDocument

/**
 * Item in *AdvisorSection → Default → Primary → Badges*
 */
export interface AdvisorSectionSliceDefaultPrimaryBadgesItem {
  /**
   * title field in *AdvisorSection → Default → Primary → Badges*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_section.default.primary.badges[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField
}

/**
 * Primary content in *AdvisorSection → Default → Primary*
 */
export interface AdvisorSectionSliceDefaultPrimary {
  /**
   * Badges field in *AdvisorSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_section.default.primary.badges[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  badges: prismic.GroupField<Simplify<AdvisorSectionSliceDefaultPrimaryBadgesItem>>

  /**
   * title field in *AdvisorSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * description field in *AdvisorSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField
}

/**
 * Default variation for AdvisorSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AdvisorSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<AdvisorSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *AdvisorSection*
 */
type AdvisorSectionSliceVariation = AdvisorSectionSliceDefault

/**
 * AdvisorSection Shared Slice
 *
 * - **API ID**: `advisor_section`
 * - **Description**: AdvisorSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AdvisorSectionSlice = prismic.SharedSlice<
  'advisor_section',
  AdvisorSectionSliceVariation
>

/**
 * Primary content in *Bio → Default → Primary*
 */
export interface BioSliceDefaultPrimary {
  /**
   * Title field in *Bio → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * content field in *Bio → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField

  /**
   * image field in *Bio → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bio.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>

  /**
   * button field in *Bio → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: bio.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Default variation for Bio Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BioSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<BioSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Bio*
 */
type BioSliceVariation = BioSliceDefault

/**
 * Bio Shared Slice
 *
 * - **API ID**: `bio`
 * - **Description**: Bio
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BioSlice = prismic.SharedSlice<'bio', BioSliceVariation>

/**
 * Primary content in *BlogHome → Default → Primary*
 */
export interface BlogHomeSliceDefaultPrimary {
  /**
   * title field in *BlogHome → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_home.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * description field in *BlogHome → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_home.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField
}

/**
 * Default variation for BlogHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogHomeSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<BlogHomeSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *BlogHome*
 */
type BlogHomeSliceVariation = BlogHomeSliceDefault

/**
 * BlogHome Shared Slice
 *
 * - **API ID**: `blog_home`
 * - **Description**: BlogHome
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogHomeSlice = prismic.SharedSlice<'blog_home', BlogHomeSliceVariation>

/**
 * Item in *ContactUs → Default → Primary → form*
 */
export interface ContactUsSliceDefaultPrimaryFormItem {
  /**
   * label field in *ContactUs → Default → Primary → form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.form[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField

  /**
   * placeholder field in *ContactUs → Default → Primary → form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.form[].placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder: prismic.KeyTextField
}

/**
 * Primary content in *ContactUs → Default → Primary*
 */
export interface ContactUsSliceDefaultPrimary {
  /**
   * title field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * description field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField

  /**
   * form field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.form[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  form: prismic.GroupField<Simplify<ContactUsSliceDefaultPrimaryFormItem>>

  /**
   * button text field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField
}

/**
 * Default variation for ContactUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactUsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContactUsSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ContactUs*
 */
type ContactUsSliceVariation = ContactUsSliceDefault

/**
 * ContactUs Shared Slice
 *
 * - **API ID**: `contact_us`
 * - **Description**: ContactUs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactUsSlice = prismic.SharedSlice<'contact_us', ContactUsSliceVariation>

/**
 * Item in *FaqSection → Default → Primary → Question and Answers*
 */
export interface FaqSectionSliceDefaultPrimaryQuestionAndAnswersItem {
  /**
   * Question field in *FaqSection → Default → Primary → Question and Answers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.question_and_answers[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField

  /**
   * Answers field in *FaqSection → Default → Primary → Question and Answers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.question_and_answers[].answers
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  answers: prismic.KeyTextField
}

/**
 * Primary content in *FaqSection → Default → Primary*
 */
export interface FaqSectionSliceDefaultPrimary {
  /**
   * Title field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Question and Answers field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.question_and_answers[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  question_and_answers: prismic.GroupField<
    Simplify<FaqSectionSliceDefaultPrimaryQuestionAndAnswersItem>
  >
}

/**
 * Default variation for FaqSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FaqSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *FaqSection*
 */
type FaqSectionSliceVariation = FaqSectionSliceDefault

/**
 * FaqSection Shared Slice
 *
 * - **API ID**: `faq_section`
 * - **Description**: FaqSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSectionSlice = prismic.SharedSlice<'faq_section', FaqSectionSliceVariation>

/**
 * Primary content in *FeaturedSection → Default → Primary*
 */
export interface FeaturedSectionSliceDefaultPrimary {
  /**
   * Image field in *FeaturedSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>

  /**
   * Title field in *FeaturedSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField
}

/**
 * Default variation for FeaturedSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FeaturedSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *FeaturedSection*
 */
type FeaturedSectionSliceVariation = FeaturedSectionSliceDefault

/**
 * FeaturedSection Shared Slice
 *
 * - **API ID**: `featured_section`
 * - **Description**: FeaturedSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedSectionSlice = prismic.SharedSlice<
  'featured_section',
  FeaturedSectionSliceVariation
>

/**
 * Item in *Footer → Default → Primary → About*
 */
export interface FooterSliceDefaultPrimaryAboutItem {
  /**
   * Link Item field in *Footer → Default → Primary → About*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.about[].link_item
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_item: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Logo Brand field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logo_brand
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo_brand: prismic.ImageField<never>

  /**
   * Brand name field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.brand_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  brand_name: prismic.KeyTextField

  /**
   * Linkedin Link field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.linkedin_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedin_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * About field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.about[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  about: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryAboutItem>>

  /**
   * Privacy Policy field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.privacy_policy
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  privacy_policy: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Terms of Use field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.terms_of_use
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  terms_of_use: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * All Rights Reserved  field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.all_rights_reserved
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  all_rights_reserved: prismic.KeyTextField
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FooterSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<'footer', FooterSliceVariation>

/**
 * Item in *Hero → Default → Primary → carousel_images*
 */
export interface HeroSliceDefaultPrimaryCarouselImagesItem {
  /**
   * image field in *Hero → Default → Primary → carousel_images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel_images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Turn your financial dreams into reality
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * video url field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.video_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  video_url: prismic.KeyTextField

  /**
   * carousel_images field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel_images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  carousel_images: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryCarouselImagesItem>>

  /**
   * carousel_mode field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  carousel_mode: prismic.SelectField<
    'fade_transition' | 'slide_transition' | 'zoom_fade' | 'parallax_effect' | 'ken_burns_effect'
  >
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>

/**
 * Primary content in *MarkdownContent → Default → Primary*
 */
export interface MarkdownContentSliceDefaultPrimary {
  /**
   * Title field in *MarkdownContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: markdown_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * Last Updated At field in *MarkdownContent → Default → Primary*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: markdown_content.default.primary.last_updated_at
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  last_updated_at: prismic.TimestampField

  /**
   * content field in *MarkdownContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: markdown_content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField
}

/**
 * Default variation for MarkdownContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarkdownContentSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MarkdownContentSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *MarkdownContent*
 */
type MarkdownContentSliceVariation = MarkdownContentSliceDefault

/**
 * MarkdownContent Shared Slice
 *
 * - **API ID**: `markdown_content`
 * - **Description**: MarkdownContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarkdownContentSlice = prismic.SharedSlice<
  'markdown_content',
  MarkdownContentSliceVariation
>

/**
 * Primary content in *MasteredSection → Default → Primary*
 */
export interface MasteredSectionSliceDefaultPrimary {
  /**
   * Title field in *MasteredSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mastered_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * description field in *MasteredSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mastered_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Button field in *MasteredSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mastered_section.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * For Illustrative Purposes Only field in *MasteredSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mastered_section.default.primary.for_illustrative_purposes_only
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  for_illustrative_purposes_only: prismic.ImageField<never>
}

/**
 * Default variation for MasteredSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MasteredSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MasteredSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *MasteredSection*
 */
type MasteredSectionSliceVariation = MasteredSectionSliceDefault

/**
 * MasteredSection Shared Slice
 *
 * - **API ID**: `mastered_section`
 * - **Description**: MasteredSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MasteredSectionSlice = prismic.SharedSlice<
  'mastered_section',
  MasteredSectionSliceVariation
>

/**
 * Item in *MembershipSection → Default → Primary → cards*
 */
export interface MembershipSectionSliceDefaultPrimaryCardsItem {
  /**
   * Icon field in *MembershipSection → Default → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>

  /**
   * Title field in *MembershipSection → Default → Primary → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Description field in *MembershipSection → Default → Primary → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField
}

/**
 * Primary content in *MembershipSection → Default → Primary*
 */
export interface MembershipSectionSliceDefaultPrimary {
  /**
   * Title field in *MembershipSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *MembershipSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Button field in *MembershipSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * citation_text field in *MembershipSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.citation_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  citation_text: prismic.RichTextField

  /**
   * cards field in *MembershipSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<MembershipSectionSliceDefaultPrimaryCardsItem>>
}

/**
 * Default variation for MembershipSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MembershipSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MembershipSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *MembershipSection*
 */
type MembershipSectionSliceVariation = MembershipSectionSliceDefault

/**
 * MembershipSection Shared Slice
 *
 * - **API ID**: `membership_section`
 * - **Description**: MembershipSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MembershipSectionSlice = prismic.SharedSlice<
  'membership_section',
  MembershipSectionSliceVariation
>

/**
 * Item in *Navbar → Default → Primary → AboutGroup*
 */
export interface NavbarSliceDefaultPrimaryAboutgroupItem {
  /**
   * About Item field in *Navbar → Default → Primary → AboutGroup*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.aboutgroup[].about_item
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  about_item: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Primary content in *Navbar → Default → Primary*
 */
export interface NavbarSliceDefaultPrimary {
  /**
   * Logo Image field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>

  /**
   * Login field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.login
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  login: prismic.LinkField<string, string, unknown, prismic.FieldState, 'Primary' | 'Secondary'>

  /**
   * Free Strategy Session field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.free_strategy_session
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  free_strategy_session: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * AboutGroup field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.aboutgroup[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  aboutgroup: prismic.GroupField<Simplify<NavbarSliceDefaultPrimaryAboutgroupItem>>

  /**
   * Pricing field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.pricing
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  pricing: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Blog field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.blog
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  blog: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Default variation for Navbar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavbarSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<NavbarSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Navbar*
 */
type NavbarSliceVariation = NavbarSliceDefault

/**
 * Navbar Shared Slice
 *
 * - **API ID**: `navbar`
 * - **Description**: Navbar
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavbarSlice = prismic.SharedSlice<'navbar', NavbarSliceVariation>

/**
 * Item in *OurProcess → Default → Primary → Process Step*
 */
export interface OurProcessSliceDefaultPrimaryProcessStepItem {
  /**
   * icon field in *OurProcess → Default → Primary → Process Step*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_process.default.primary.process_step[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>

  /**
   * title field in *OurProcess → Default → Primary → Process Step*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_process.default.primary.process_step[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * description field in *OurProcess → Default → Primary → Process Step*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_process.default.primary.process_step[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField
}

/**
 * Primary content in *OurProcess → Default → Primary*
 */
export interface OurProcessSliceDefaultPrimary {
  /**
   * Title field in *OurProcess → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_process.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *OurProcess → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_process.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField

  /**
   * Process Step field in *OurProcess → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: our_process.default.primary.process_step[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  process_step: prismic.GroupField<Simplify<OurProcessSliceDefaultPrimaryProcessStepItem>>

  /**
   * Result title field in *OurProcess → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_process.default.primary.result_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  result_title: prismic.KeyTextField

  /**
   * Result description field in *OurProcess → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_process.default.primary.result_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  result_description: prismic.KeyTextField

  /**
   * Button text field in *OurProcess → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: our_process.default.primary.apply_to_membership
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  apply_to_membership: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Default variation for OurProcess Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurProcessSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<OurProcessSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *OurProcess*
 */
type OurProcessSliceVariation = OurProcessSliceDefault

/**
 * OurProcess Shared Slice
 *
 * - **API ID**: `our_process`
 * - **Description**: OurProcess
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurProcessSlice = prismic.SharedSlice<'our_process', OurProcessSliceVariation>

/**
 * Primary content in *PricingPage → Default → Primary*
 */
export interface PricingPageSliceDefaultPrimary {
  /**
   * title field in *PricingPage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_page.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * description field in *PricingPage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_page.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField
}

/**
 * Default variation for PricingPage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PricingPageSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<PricingPageSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *PricingPage*
 */
type PricingPageSliceVariation = PricingPageSliceDefault

/**
 * PricingPage Shared Slice
 *
 * - **API ID**: `pricing_page`
 * - **Description**: PricingPage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PricingPageSlice = prismic.SharedSlice<'pricing_page', PricingPageSliceVariation>

/**
 * Item in *ProcessSection → Default → Primary → cards*
 */
export interface ProcessSectionSliceDefaultPrimaryCardsItem {
  /**
   * step image field in *ProcessSection → Default → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.cards[].step_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  step_image: prismic.ImageField<never>
}

/**
 * Primary content in *ProcessSection → Default → Primary*
 */
export interface ProcessSectionSliceDefaultPrimary {
  /**
   * Title field in *ProcessSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Description field in *ProcessSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.descriptiomn
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  descriptiomn: prismic.KeyTextField

  /**
   * Button field in *ProcessSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * cards field in *ProcessSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<ProcessSectionSliceDefaultPrimaryCardsItem>>
}

/**
 * Default variation for ProcessSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ProcessSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ProcessSection*
 */
type ProcessSectionSliceVariation = ProcessSectionSliceDefault

/**
 * ProcessSection Shared Slice
 *
 * - **API ID**: `process_section`
 * - **Description**: ProcessSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessSectionSlice = prismic.SharedSlice<
  'process_section',
  ProcessSectionSliceVariation
>

/**
 * Item in *ServiceSection → Default → Primary → Services*
 */
export interface ServiceSectionSliceDefaultPrimaryServicesItem {
  /**
   * logo field in *ServiceSection → Default → Primary → Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.services[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>

  /**
   * title field in *ServiceSection → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.services[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * description field in *ServiceSection → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.services[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField
}

/**
 * Primary content in *ServiceSection → Default → Primary*
 */
export interface ServiceSectionSliceDefaultPrimary {
  /**
   * title field in *ServiceSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * description field in *ServiceSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField

  /**
   * Services field in *ServiceSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services: prismic.GroupField<Simplify<ServiceSectionSliceDefaultPrimaryServicesItem>>
}

/**
 * Default variation for ServiceSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ServiceSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ServiceSection*
 */
type ServiceSectionSliceVariation = ServiceSectionSliceDefault

/**
 * ServiceSection Shared Slice
 *
 * - **API ID**: `service_section`
 * - **Description**: ServiceSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceSectionSlice = prismic.SharedSlice<
  'service_section',
  ServiceSectionSliceVariation
>

/**
 * Item in *TestimonialsSection → Default → Primary → cards*
 */
export interface TestimonialsSectionSliceDefaultPrimaryCardsItem {
  /**
   * star_number field in *TestimonialsSection → Default → Primary → cards*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.cards[].star_number
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  star_number: prismic.NumberField

  /**
   * review_content field in *TestimonialsSection → Default → Primary → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.cards[].review_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  review_content: prismic.RichTextField

  /**
   * avatar field in *TestimonialsSection → Default → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.cards[].avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>

  /**
   * Username field in *TestimonialsSection → Default → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.cards[].username
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  username: prismic.KeyTextField
}

/**
 * Primary content in *TestimonialsSection → Default → Primary*
 */
export interface TestimonialsSectionSliceDefaultPrimary {
  /**
   * Title field in *TestimonialsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * star_number field in *TestimonialsSection → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.star_number
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  star_number: prismic.NumberField

  /**
   * See more button field in *TestimonialsSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.see_more_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  see_more_button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * citation_text field in *TestimonialsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.citation_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  citation_text: prismic.RichTextField

  /**
   * cards field in *TestimonialsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<TestimonialsSectionSliceDefaultPrimaryCardsItem>>
}

/**
 * Default variation for TestimonialsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TestimonialsSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *TestimonialsSection*
 */
type TestimonialsSectionSliceVariation = TestimonialsSectionSliceDefault

/**
 * TestimonialsSection Shared Slice
 *
 * - **API ID**: `testimonials_section`
 * - **Description**: TestimonialsSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSectionSlice = prismic.SharedSlice<
  'testimonials_section',
  TestimonialsSectionSliceVariation
>

/**
 * Item in *WhyDomainSection → Default → Primary → cards*
 */
export interface WhyDomainSectionSliceDefaultPrimaryCardsItem {
  /**
   * Icon field in *WhyDomainSection → Default → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: why_domain_section.default.primary.cards[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>

  /**
   * Title field in *WhyDomainSection → Default → Primary → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_domain_section.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Description field in *WhyDomainSection → Default → Primary → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_domain_section.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField
}

/**
 * Primary content in *WhyDomainSection → Default → Primary*
 */
export interface WhyDomainSectionSliceDefaultPrimary {
  /**
   * cards field in *WhyDomainSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: why_domain_section.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<WhyDomainSectionSliceDefaultPrimaryCardsItem>>
}

/**
 * Default variation for WhyDomainSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhyDomainSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<WhyDomainSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *WhyDomainSection*
 */
type WhyDomainSectionSliceVariation = WhyDomainSectionSliceDefault

/**
 * WhyDomainSection Shared Slice
 *
 * - **API ID**: `why_domain_section`
 * - **Description**: WhyDomainSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhyDomainSectionSlice = prismic.SharedSlice<
  'why_domain_section',
  WhyDomainSectionSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>
  }

  namespace Content {
    export type {
      BlogListingDocument,
      BlogListingDocumentData,
      BlogListingDocumentDataSlicesSlice,
      BlogPageDocument,
      BlogPageDocumentData,
      BlogPageDocumentDataSlicesSlice,
      BlogPageNewDocument,
      BlogPageNewDocumentData,
      BlogPageNewDocumentDataSlicesSlice,
      ContactUsDocument,
      ContactUsDocumentData,
      ContactUsDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      LandingDocument,
      LandingDocumentData,
      LandingDocumentDataSlicesSlice,
      OurProcessDocument,
      OurProcessDocumentData,
      OurProcessDocumentDataSlicesSlice,
      PricingPageDocument,
      PricingPageDocumentData,
      PricingPageDocumentDataSlicesSlice,
      PrivacyPolicyDocument,
      PrivacyPolicyDocumentData,
      PrivacyPolicyDocumentDataSlicesSlice,
      TermOfServicesDocument,
      TermOfServicesDocumentData,
      TermOfServicesDocumentDataSlicesSlice,
      AllDocumentTypes,
      AdvisorSectionSlice,
      AdvisorSectionSliceDefaultPrimaryBadgesItem,
      AdvisorSectionSliceDefaultPrimary,
      AdvisorSectionSliceVariation,
      AdvisorSectionSliceDefault,
      BioSlice,
      BioSliceDefaultPrimary,
      BioSliceVariation,
      BioSliceDefault,
      BlogHomeSlice,
      BlogHomeSliceDefaultPrimary,
      BlogHomeSliceVariation,
      BlogHomeSliceDefault,
      ContactUsSlice,
      ContactUsSliceDefaultPrimaryFormItem,
      ContactUsSliceDefaultPrimary,
      ContactUsSliceVariation,
      ContactUsSliceDefault,
      FaqSectionSlice,
      FaqSectionSliceDefaultPrimaryQuestionAndAnswersItem,
      FaqSectionSliceDefaultPrimary,
      FaqSectionSliceVariation,
      FaqSectionSliceDefault,
      FeaturedSectionSlice,
      FeaturedSectionSliceDefaultPrimary,
      FeaturedSectionSliceVariation,
      FeaturedSectionSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimaryAboutItem,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryCarouselImagesItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      MarkdownContentSlice,
      MarkdownContentSliceDefaultPrimary,
      MarkdownContentSliceVariation,
      MarkdownContentSliceDefault,
      MasteredSectionSlice,
      MasteredSectionSliceDefaultPrimary,
      MasteredSectionSliceVariation,
      MasteredSectionSliceDefault,
      MembershipSectionSlice,
      MembershipSectionSliceDefaultPrimaryCardsItem,
      MembershipSectionSliceDefaultPrimary,
      MembershipSectionSliceVariation,
      MembershipSectionSliceDefault,
      NavbarSlice,
      NavbarSliceDefaultPrimaryAboutgroupItem,
      NavbarSliceDefaultPrimary,
      NavbarSliceVariation,
      NavbarSliceDefault,
      OurProcessSlice,
      OurProcessSliceDefaultPrimaryProcessStepItem,
      OurProcessSliceDefaultPrimary,
      OurProcessSliceVariation,
      OurProcessSliceDefault,
      PricingPageSlice,
      PricingPageSliceDefaultPrimary,
      PricingPageSliceVariation,
      PricingPageSliceDefault,
      ProcessSectionSlice,
      ProcessSectionSliceDefaultPrimaryCardsItem,
      ProcessSectionSliceDefaultPrimary,
      ProcessSectionSliceVariation,
      ProcessSectionSliceDefault,
      ServiceSectionSlice,
      ServiceSectionSliceDefaultPrimaryServicesItem,
      ServiceSectionSliceDefaultPrimary,
      ServiceSectionSliceVariation,
      ServiceSectionSliceDefault,
      TestimonialsSectionSlice,
      TestimonialsSectionSliceDefaultPrimaryCardsItem,
      TestimonialsSectionSliceDefaultPrimary,
      TestimonialsSectionSliceVariation,
      TestimonialsSectionSliceDefault,
      WhyDomainSectionSlice,
      WhyDomainSectionSliceDefaultPrimaryCardsItem,
      WhyDomainSectionSliceDefaultPrimary,
      WhyDomainSectionSliceVariation,
      WhyDomainSectionSliceDefault,
    }
  }
}
