// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship['id']]: ContentRelationshipFieldWithData<
      TSubRelationship['customtypes'],
      TLang
    >
  } & // Group
  {
    [TGroup in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
      : never
  } & // Other fields
  {
    [TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
      ? TData[TFieldKey]
      : never
  }

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
      TLang
    >
  >
}[Exclude<TCustomType[number], string>['id']]

type LandingDocumentDataSlicesSlice =
  | FooterSlice
  | ServiceSectionSlice
  | ProcessSectionSlice
  | TestimonialsSectionSlice
  | WhyDomainSectionSlice
  | FaqSectionSlice
  | MasteredSectionSlice
  | AdvisorSectionSlice
  | MembershipSectionSlice
  | FeaturedSectionSlice
  | NavbarSlice
  | HeroSlice

/**
 * Content for Landing documents
 */
interface LandingDocumentData {
  /**
   * Slice Zone field in *Landing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LandingDocumentDataSlicesSlice> /**
   * Meta Title field in *Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Landing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Landing document from Prismic
 *
 * - **API ID**: `landing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<LandingDocumentData>,
  'landing',
  Lang
>

export type AllDocumentTypes = LandingDocument

/**
 * Item in *AdvisorSection → Default → Primary → Badges*
 */
export interface AdvisorSectionSliceDefaultPrimaryBadgesItem {
  /**
   * title field in *AdvisorSection → Default → Primary → Badges*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_section.default.primary.badges[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField
}

/**
 * Primary content in *AdvisorSection → Default → Primary*
 */
export interface AdvisorSectionSliceDefaultPrimary {
  /**
   * title field in *AdvisorSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * description field in *AdvisorSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Badges field in *AdvisorSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_section.default.primary.badges[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  badges: prismic.GroupField<Simplify<AdvisorSectionSliceDefaultPrimaryBadgesItem>>

  /**
   * Button field in *AdvisorSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_section.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Default variation for AdvisorSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AdvisorSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<AdvisorSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *AdvisorSection*
 */
type AdvisorSectionSliceVariation = AdvisorSectionSliceDefault

/**
 * AdvisorSection Shared Slice
 *
 * - **API ID**: `advisor_section`
 * - **Description**: AdvisorSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AdvisorSectionSlice = prismic.SharedSlice<
  'advisor_section',
  AdvisorSectionSliceVariation
>

/**
 * Item in *FaqSection → Default → Primary → Question and Answers*
 */
export interface FaqSectionSliceDefaultPrimaryQuestionAndAnswersItem {
  /**
   * Question field in *FaqSection → Default → Primary → Question and Answers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.question_and_answers[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField

  /**
   * Answers field in *FaqSection → Default → Primary → Question and Answers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.question_and_answers[].answers
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  answers: prismic.KeyTextField
}

/**
 * Primary content in *FaqSection → Default → Primary*
 */
export interface FaqSectionSliceDefaultPrimary {
  /**
   * Title field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Question and Answers field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.question_and_answers[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  question_and_answers: prismic.GroupField<
    Simplify<FaqSectionSliceDefaultPrimaryQuestionAndAnswersItem>
  >
}

/**
 * Default variation for FaqSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FaqSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *FaqSection*
 */
type FaqSectionSliceVariation = FaqSectionSliceDefault

/**
 * FaqSection Shared Slice
 *
 * - **API ID**: `faq_section`
 * - **Description**: FaqSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSectionSlice = prismic.SharedSlice<'faq_section', FaqSectionSliceVariation>

/**
 * Primary content in *FeaturedSection → Default → Primary*
 */
export interface FeaturedSectionSliceDefaultPrimary {
  /**
   * Image field in *FeaturedSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>

  /**
   * Title field in *FeaturedSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField
}

/**
 * Default variation for FeaturedSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FeaturedSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *FeaturedSection*
 */
type FeaturedSectionSliceVariation = FeaturedSectionSliceDefault

/**
 * FeaturedSection Shared Slice
 *
 * - **API ID**: `featured_section`
 * - **Description**: FeaturedSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedSectionSlice = prismic.SharedSlice<
  'featured_section',
  FeaturedSectionSliceVariation
>

/**
 * Item in *Footer → Default → Primary → About*
 */
export interface FooterSliceDefaultPrimaryAboutItem {
  /**
   * Link Item field in *Footer → Default → Primary → About*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.about[].link_item
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_item: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Item in *Footer → Default → Primary → Services*
 */
export interface FooterSliceDefaultPrimaryServicesItem {
  /**
   * Link Item field in *Footer → Default → Primary → Services*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.services[].link_item
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_item: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Item in *Footer → Default → Primary → Meet Our Advisors*
 */
export interface FooterSliceDefaultPrimaryMeetOurAdvisorsItem {
  /**
   * Link Item field in *Footer → Default → Primary → Meet Our Advisors*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.meet_our_advisors[].link_item
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_item: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Item in *Footer → Default → Primary → Resources*
 */
export interface FooterSliceDefaultPrimaryResourcesItem {
  /**
   * Link Item field in *Footer → Default → Primary → Resources*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.resources[].link_item
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_item: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Item in *Footer → Default → Primary → Plans*
 */
export interface FooterSliceDefaultPrimaryPlansItem {
  /**
   * Link Item field in *Footer → Default → Primary → Plans*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.plans[].link_item
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_item: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Logo Brand field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logo_brand
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo_brand: prismic.ImageField<never>

  /**
   * Brand name field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.brand_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  brand_name: prismic.KeyTextField

  /**
   * Instagram Link field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.instagram_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  instagram_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Linkedin Link field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.linkedin_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedin_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Twitter Link field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.twitter_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  twitter_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * About field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.about[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  about: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryAboutItem>>

  /**
   * Services field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryServicesItem>>

  /**
   * Meet Our Advisors field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.meet_our_advisors[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  meet_our_advisors: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryMeetOurAdvisorsItem>>

  /**
   * Resources field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.resources[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  resources: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryResourcesItem>>

  /**
   * Plans field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.plans[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  plans: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryPlansItem>>

  /**
   * Copyright1 field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.copyright1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright1: prismic.KeyTextField

  /**
   * Copyright2 field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.copyright2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright2: prismic.KeyTextField

  /**
   * All Rights Reserved field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.all_rights_reserved
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  all_rights_reserved: prismic.KeyTextField

  /**
   * Log In field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.log_in
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  log_in: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Privacy Policy field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.privacy_policy
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  privacy_policy: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Terms of Use field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.terms_of_use
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  terms_of_use: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Form ADV field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.form_adv
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  form_adv: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Legal field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.legal
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  legal: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Form CRS field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.form_crs
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  form_crs: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FooterSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<'footer', FooterSliceVariation>

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Turn your financial dreams into reality
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * video url field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.video_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  video_url: prismic.KeyTextField
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>

/**
 * Primary content in *MasteredSection → Default → Primary*
 */
export interface MasteredSectionSliceDefaultPrimary {
  /**
   * Title field in *MasteredSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mastered_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * description field in *MasteredSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mastered_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Button field in *MasteredSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mastered_section.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * For Illustrative Purposes Only field in *MasteredSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mastered_section.default.primary.for_illustrative_purposes_only
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  for_illustrative_purposes_only: prismic.ImageField<never>
}

/**
 * Default variation for MasteredSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MasteredSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MasteredSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *MasteredSection*
 */
type MasteredSectionSliceVariation = MasteredSectionSliceDefault

/**
 * MasteredSection Shared Slice
 *
 * - **API ID**: `mastered_section`
 * - **Description**: MasteredSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MasteredSectionSlice = prismic.SharedSlice<
  'mastered_section',
  MasteredSectionSliceVariation
>

/**
 * Item in *MembershipSection → Default → Primary → cards*
 */
export interface MembershipSectionSliceDefaultPrimaryCardsItem {
  /**
   * Icon field in *MembershipSection → Default → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>

  /**
   * Title field in *MembershipSection → Default → Primary → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Description field in *MembershipSection → Default → Primary → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField
}

/**
 * Primary content in *MembershipSection → Default → Primary*
 */
export interface MembershipSectionSliceDefaultPrimary {
  /**
   * Title field in *MembershipSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *MembershipSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Button field in *MembershipSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * citation_text field in *MembershipSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.citation_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  citation_text: prismic.RichTextField

  /**
   * cards field in *MembershipSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_section.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<MembershipSectionSliceDefaultPrimaryCardsItem>>
}

/**
 * Default variation for MembershipSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MembershipSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MembershipSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *MembershipSection*
 */
type MembershipSectionSliceVariation = MembershipSectionSliceDefault

/**
 * MembershipSection Shared Slice
 *
 * - **API ID**: `membership_section`
 * - **Description**: MembershipSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MembershipSectionSlice = prismic.SharedSlice<
  'membership_section',
  MembershipSectionSliceVariation
>

/**
 * Primary content in *Navbar → Default → Primary*
 */
export interface NavbarSliceDefaultPrimary {
  /**
   * Logo Image field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>

  /**
   * Logo name field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.logo_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  logo_name: prismic.KeyTextField

  /**
   * About field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.about
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  about: prismic.Repeatable<prismic.LinkField<string, string, unknown, prismic.FieldState, never>>

  /**
   * Membership field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.membership
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  membership: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >

  /**
   * Pricing field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.pricing
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  pricing: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Services field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.services
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  services: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >

  /**
   * Learn field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.learn
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  learn: prismic.Repeatable<prismic.LinkField<string, string, unknown, prismic.FieldState, never>>

  /**
   * Resources field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.resources
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  resources: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >

  /**
   * Login field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.login
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  login: prismic.LinkField<string, string, unknown, prismic.FieldState, 'Primary' | 'Secondary'>

  /**
   * Free Strategy Session field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.free_strategy_session
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  free_strategy_session: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Default variation for Navbar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavbarSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<NavbarSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Navbar*
 */
type NavbarSliceVariation = NavbarSliceDefault

/**
 * Navbar Shared Slice
 *
 * - **API ID**: `navbar`
 * - **Description**: Navbar
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavbarSlice = prismic.SharedSlice<'navbar', NavbarSliceVariation>

/**
 * Item in *ProcessSection → Default → Primary → cards*
 */
export interface ProcessSectionSliceDefaultPrimaryCardsItem {
  /**
   * step image field in *ProcessSection → Default → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.cards[].step_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  step_image: prismic.ImageField<never>
}

/**
 * Primary content in *ProcessSection → Default → Primary*
 */
export interface ProcessSectionSliceDefaultPrimary {
  /**
   * Title field in *ProcessSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Description field in *ProcessSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.descriptiomn
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  descriptiomn: prismic.KeyTextField

  /**
   * Button field in *ProcessSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * cards field in *ProcessSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<ProcessSectionSliceDefaultPrimaryCardsItem>>
}

/**
 * Default variation for ProcessSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ProcessSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ProcessSection*
 */
type ProcessSectionSliceVariation = ProcessSectionSliceDefault

/**
 * ProcessSection Shared Slice
 *
 * - **API ID**: `process_section`
 * - **Description**: ProcessSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessSectionSlice = prismic.SharedSlice<
  'process_section',
  ProcessSectionSliceVariation
>

/**
 * Item in *ServiceSection → Default → Primary → Services*
 */
export interface ServiceSectionSliceDefaultPrimaryServicesItem {
  /**
   * logo field in *ServiceSection → Default → Primary → Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.services[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>

  /**
   * title field in *ServiceSection → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.services[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * description field in *ServiceSection → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.services[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField
}

/**
 * Primary content in *ServiceSection → Default → Primary*
 */
export interface ServiceSectionSliceDefaultPrimary {
  /**
   * Services field in *ServiceSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services: prismic.GroupField<Simplify<ServiceSectionSliceDefaultPrimaryServicesItem>>
}

/**
 * Default variation for ServiceSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ServiceSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ServiceSection*
 */
type ServiceSectionSliceVariation = ServiceSectionSliceDefault

/**
 * ServiceSection Shared Slice
 *
 * - **API ID**: `service_section`
 * - **Description**: ServiceSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceSectionSlice = prismic.SharedSlice<
  'service_section',
  ServiceSectionSliceVariation
>

/**
 * Item in *TestimonialsSection → Default → Primary → cards*
 */
export interface TestimonialsSectionSliceDefaultPrimaryCardsItem {
  /**
   * star_number field in *TestimonialsSection → Default → Primary → cards*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.cards[].star_number
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  star_number: prismic.NumberField

  /**
   * review_content field in *TestimonialsSection → Default → Primary → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.cards[].review_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  review_content: prismic.RichTextField

  /**
   * avatar field in *TestimonialsSection → Default → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.cards[].avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>

  /**
   * Username field in *TestimonialsSection → Default → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.cards[].username
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  username: prismic.KeyTextField
}

/**
 * Primary content in *TestimonialsSection → Default → Primary*
 */
export interface TestimonialsSectionSliceDefaultPrimary {
  /**
   * Title field in *TestimonialsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * star_number field in *TestimonialsSection → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.star_number
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  star_number: prismic.NumberField

  /**
   * See more button field in *TestimonialsSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.see_more_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  see_more_button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * citation_text field in *TestimonialsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.citation_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  citation_text: prismic.RichTextField

  /**
   * cards field in *TestimonialsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<TestimonialsSectionSliceDefaultPrimaryCardsItem>>
}

/**
 * Default variation for TestimonialsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TestimonialsSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *TestimonialsSection*
 */
type TestimonialsSectionSliceVariation = TestimonialsSectionSliceDefault

/**
 * TestimonialsSection Shared Slice
 *
 * - **API ID**: `testimonials_section`
 * - **Description**: TestimonialsSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSectionSlice = prismic.SharedSlice<
  'testimonials_section',
  TestimonialsSectionSliceVariation
>

/**
 * Item in *WhyDomainSection → Default → Primary → cards*
 */
export interface WhyDomainSectionSliceDefaultPrimaryCardsItem {
  /**
   * Icon field in *WhyDomainSection → Default → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: why_domain_section.default.primary.cards[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>

  /**
   * Title field in *WhyDomainSection → Default → Primary → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_domain_section.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Description field in *WhyDomainSection → Default → Primary → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_domain_section.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField
}

/**
 * Primary content in *WhyDomainSection → Default → Primary*
 */
export interface WhyDomainSectionSliceDefaultPrimary {
  /**
   * cards field in *WhyDomainSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: why_domain_section.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<WhyDomainSectionSliceDefaultPrimaryCardsItem>>
}

/**
 * Default variation for WhyDomainSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhyDomainSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<WhyDomainSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *WhyDomainSection*
 */
type WhyDomainSectionSliceVariation = WhyDomainSectionSliceDefault

/**
 * WhyDomainSection Shared Slice
 *
 * - **API ID**: `why_domain_section`
 * - **Description**: WhyDomainSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhyDomainSectionSlice = prismic.SharedSlice<
  'why_domain_section',
  WhyDomainSectionSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>
  }

  namespace Content {
    export type {
      LandingDocument,
      LandingDocumentData,
      LandingDocumentDataSlicesSlice,
      AllDocumentTypes,
      AdvisorSectionSlice,
      AdvisorSectionSliceDefaultPrimaryBadgesItem,
      AdvisorSectionSliceDefaultPrimary,
      AdvisorSectionSliceVariation,
      AdvisorSectionSliceDefault,
      FaqSectionSlice,
      FaqSectionSliceDefaultPrimaryQuestionAndAnswersItem,
      FaqSectionSliceDefaultPrimary,
      FaqSectionSliceVariation,
      FaqSectionSliceDefault,
      FeaturedSectionSlice,
      FeaturedSectionSliceDefaultPrimary,
      FeaturedSectionSliceVariation,
      FeaturedSectionSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimaryAboutItem,
      FooterSliceDefaultPrimaryServicesItem,
      FooterSliceDefaultPrimaryMeetOurAdvisorsItem,
      FooterSliceDefaultPrimaryResourcesItem,
      FooterSliceDefaultPrimaryPlansItem,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      MasteredSectionSlice,
      MasteredSectionSliceDefaultPrimary,
      MasteredSectionSliceVariation,
      MasteredSectionSliceDefault,
      MembershipSectionSlice,
      MembershipSectionSliceDefaultPrimaryCardsItem,
      MembershipSectionSliceDefaultPrimary,
      MembershipSectionSliceVariation,
      MembershipSectionSliceDefault,
      NavbarSlice,
      NavbarSliceDefaultPrimary,
      NavbarSliceVariation,
      NavbarSliceDefault,
      ProcessSectionSlice,
      ProcessSectionSliceDefaultPrimaryCardsItem,
      ProcessSectionSliceDefaultPrimary,
      ProcessSectionSliceVariation,
      ProcessSectionSliceDefault,
      ServiceSectionSlice,
      ServiceSectionSliceDefaultPrimaryServicesItem,
      ServiceSectionSliceDefaultPrimary,
      ServiceSectionSliceVariation,
      ServiceSectionSliceDefault,
      TestimonialsSectionSlice,
      TestimonialsSectionSliceDefaultPrimaryCardsItem,
      TestimonialsSectionSliceDefaultPrimary,
      TestimonialsSectionSliceVariation,
      TestimonialsSectionSliceDefault,
      WhyDomainSectionSlice,
      WhyDomainSectionSliceDefaultPrimaryCardsItem,
      WhyDomainSectionSliceDefaultPrimary,
      WhyDomainSectionSliceVariation,
      WhyDomainSectionSliceDefault,
    }
  }
}
