// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  advisor_section: dynamic(() => import('./AdvisorSection')),
  faq_section: dynamic(() => import('./FaqSection')),
  featured_section: dynamic(() => import('./FeaturedSection')),
  footer: dynamic(() => import('./Footer')),
  hero: dynamic(() => import('./Hero')),
  mastered_section: dynamic(() => import('./MasteredSection')),
  membership_section: dynamic(() => import('./MembershipSection')),
  navbar: dynamic(() => import('./Navbar')),
  process_section: dynamic(() => import('./ProcessSection')),
  service_section: dynamic(() => import('./ServiceSection')),
  testimonials_section: dynamic(() => import('./TestimonialsSection')),
  why_domain_section: dynamic(() => import('./WhyDomainSection')),
}
